// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdhDQBET5WLCmyvS11fCeJGPDjPj9mFoA',
    appId: '1:902252611984:web:6a1aac5f07ebcd726e0b15',
    messagingSenderId: '902252611984',
    projectId: 'ritikpushnotifications',
    authDomain: 'ritikpushnotifications.firebaseapp.com',
    storageBucket: 'ritikpushnotifications.appspot.com',
    measurementId: 'G-H9ER5V4588',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgYLBEGi5_gK5rQhTven_65S64AEfJ25w',
    appId: '1:902252611984:android:b746a77acaef1cbd6e0b15',
    messagingSenderId: '902252611984',
    projectId: 'ritikpushnotifications',
    storageBucket: 'ritikpushnotifications.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpxK66j74PO7RNH_qWJRrwhKBYSyhdS4U',
    appId: '1:902252611984:ios:1945e13f510611446e0b15',
    messagingSenderId: '902252611984',
    projectId: 'ritikpushnotifications',
    storageBucket: 'ritikpushnotifications.appspot.com',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpxK66j74PO7RNH_qWJRrwhKBYSyhdS4U',
    appId: '1:902252611984:ios:e4253753e985d09e6e0b15',
    messagingSenderId: '902252611984',
    projectId: 'ritikpushnotifications',
    storageBucket: 'ritikpushnotifications.appspot.com',
    iosBundleId: 'com.example.admin.RunnerTests',
  );
}
